config/routes.rb
Rails.application.routes.draw do
  resources :workflows
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect("/workflows")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/workflow.rb
class Workflow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :set_workflow, only: %i[ show edit update destroy ]

  # GET /workflows or /workflows.json
  def index
    @workflows = Workflow.all
  end

  # GET /workflows/1 or /workflows/1.json
  def show
  end

  # GET /workflows/new
  def new
    @workflow = Workflow.new
  end

  # GET /workflows/1/edit
  def edit
  end

  # POST /workflows or /workflows.json
  def create
    @workflow = Workflow.new(workflow_params)

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to @workflow, notice: "Workflow was successfully created." }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflows/1 or /workflows/1.json
  def update
    respond_to do |format|
      if @workflow.update(workflow_params)
        format.html { redirect_to @workflow, notice: "Workflow was successfully updated." }
        format.json { render :show, status: :ok, location: @workflow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1 or /workflows/1.json
  def destroy
    @workflow.destroy!

    respond_to do |format|
      format.html { redirect_to workflows_path, status: :see_other, notice: "Workflow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workflow_params
      params.require(:workflow).permit(:name, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bpmn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workflows/_form.html.erb
<%= form_with(model: workflow) do |form| %>
  <% if workflow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workflow.errors.count, "error") %> prohibited this workflow from being saved:</h2>

      <ul>
        <% workflow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div data-controller="bpmn--modeler" data-bpmn--modeler-xml-value="<%= workflow.data %>">
    <%= form.label :data, style: "display: block; margin-top: 20px" %>
    <%= form.hidden_field :data, data: { bpmn__modeler_target: "xmlOutput" } %>
    <div data-bpmn--modeler-target="container" style="height: 800px; border: 1px solid black; margin-top: 5px"></div>
  </div>

  <div>
    <%= form.submit style: "margin-top: 20px" %>
  </div>
<% end %>

app/views/workflows/_workflow.html.erb
<div id="<%= dom_id workflow %>">
  <p>
    <strong>Name:</strong>
    <%= workflow.name %>
  </p>
</div>

app/views/workflows/edit.html.erb
<h1>Editing workflow</h1>

<%= render "form", workflow: @workflow %>

<br>

<div>
  <%= link_to "Show this workflow", @workflow %> |
  <%= link_to "Back to workflows", workflows_path %>
</div>

app/views/workflows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workflows</h1>

<div id="workflows">
  <% @workflows.each do |workflow| %>
    <div style="border: 1px solid black">
        <%= render workflow %>
        <p>
        <%= link_to "Show this workflow", workflow %>
        </p>
    </div>
  <% end %>
</div>

<%= link_to "New workflow", new_workflow_path %>

app/views/workflows/new.html.erb
<h1>New workflow</h1>

<%= render "form", workflow: @workflow %>

<br>

<div>
  <%= link_to "Back to workflows", workflows_path %>
</div>

app/views/workflows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workflow %>

<div data-controller="bpmn--viewer" data-bpmn--viewer-xml-value="<%= @workflow.data %>">
    <div data-bpmn--viewer-target="container" style="height: 800px; border: 1px solid black; margin-top: 5px"></div>
</div>

<div>
  <%= link_to "Edit this workflow", edit_workflow_path(@workflow) %> |
  <%= link_to "Back to workflows", workflows_path %>

  <%= button_to "Destroy this workflow", @workflow, method: :delete %>
</div>